### ISSUE TITLE
why v2sub add must be used as root?

### ISSUE THREAD

**Issue by hongyi-zhao** [airborne007/v2sub#1]
Hi,

I try to use this tool, but meet the following error:

1- 
$ v2sub add https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub
Please run as root.

2- When I use ``sudo -i'' swith to root and then run the command again, but still failed as follows:

---
v2ray/v2sub# .venv/bin/v2sub update
Traceback (most recent call last):
  File ".venv/bin/v2sub", line 10, in <module>
    sys.exit(cli())
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/v2sub/command.py", line 61, in update
    subscribe.update_subscribe(name=name, all_subs=all_subs)
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/v2sub/subscribe.py", line 99, in update_subscribe
    parser_subscribe(url, name=name)
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/v2sub/subscribe.py", line 77, in parser_subscribe
    node = utils.byte2str(base64.b64decode(node))
  File "/home/werner/software/anti-gfw/v2ray/v2sub/.venv/lib/python3.7/site-packages/v2sub/utils.py", line 30, in byte2str
    return byte.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 78: invalid start byte

---

Any hints to solve these issues?

**Comment by airborne007** [comment]
Hello, thanks for use `v2sub`!
Now, run as root is not needed except run `v2ray` command. More details please check [commit-8480c463](https://github.com/airborne007/v2sub/commit/8480c46387d1668236ababdb7ec44dc2183cc286)

The reason of `UnicodeDecodeError` looks like you subscribe source is not correct or standard, please check it again.

**Comment by airborne007** [comment]
Already done, please update to newest version.
